spring.application.name=fleet_mgmt_sys
spring.datasource.url=jdbc:postgresql://localhost:5432/fleet_mgmt_db
spring.datasource.username=postgres
spring.datasource.password=noclashfleet

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

logging.level.org.springframework.boot.context.config=DEBUG

# LTA DataMall API
lta.datamall.base-url=https://datamall2.mytransport.sg/ltaodataservice
lta.datamall.api-key=vONu3mIJRHGHsJqR7iJkpg==

# OneMap API
onemap.api-key=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNDY0MCwiZm9yZXZlciI6ZmFsc2UsImlzcyI6Ik9uZU1hcCIsImlhdCI6MTc4NDgxMDIzOCwibmJmIjoxNzg0ODEwMjM4LCJleHAiOjE3ODUwNjk0MzgsImp0aSI6ImU1N2Y4N2M1LWU4OTktNDk2Ny05MThjLTExNjE1MjUwNDcxYSJ9.bIooWBhtvcOfpzlXvfzqdot0yejI5ApKiT2SUUqZjTM9SS58syRQlSLfigCAtkiZHHJhHV33OYtQCm3kPtKropCE6LvgF5PBDnv3wYeRF2zgXk_LR-CMJNrtn4C9XLajmoZ_KNsTKvfyWAv4nWZ4CkE_PyuD6WIxo_UnOED4rTagR5UFTy_Zf1ckbtDhMuE9O-3gHFDpXxL06aTCqICoPJgSIVrXnfyDVG5fsiUVLrVqwqUMFvZc43CJvWwwLrIuZMJuHos1Vfb_1Ut6jlgJf5hMvzqz62iIC9EoKsVv8IgbbXa1h8cmiQVrn3Y7VOBl_pCyk03BEUZGq_3vRkUkpQ

# RestTemplate timeout (ms)
lta.datamall.connect-timeout=5000
lta.datamall.read-timeout=10000

# JDBC Batch inserts
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

