spring.application.name=fleet_mgmt_sys
spring.datasource.url=jdbc:postgresql://localhost:5432/fleet_mgmt_db
spring.datasource.username=postgres
spring.datasource.password=noclashfleet

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

logging.level.org.springframework.boot.context.config=DEBUG

# LTA DataMall API
lta.datamall.base-url=https://datamall2.mytransport.sg/ltaodataservice
lta.datamall.api-key=vONu3mIJRHGHsJqR7iJkpg==

# OneMap API
onemap.api-key=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNDE1MSwiZm9yZXZlciI6ZmFsc2UsImlzcyI6Ik9uZU1hcCIsImlhdCI6MTc4MTU4ODAzMiwibmJmIjoxNzgxNTg4MDMyLCJleHAiOjE3ODE4NDcyMzIsImp0aSI6ImFhMjlmNjkyLTM4ZDctNDY4My1hYzUyLTlhYzYwMTU2MDU4ZCJ9.XNyDE6yGo0VeTRQAPPfSdUzHyXI24dD4UylTmyHIZ7AV4ZdsA1XLpftoVpI6Sow08M5sH8JSC27uteFWkHs8pudkK1rTzEYVeEZ_8QEJjGDRDIueZy6WW7ZrYSeotWrIHbhObXfECOT20DyXZzrhT7S5ivc5-dKM_FjRHUb0TYQ-oRVJlod23KQdG96-5vcs-6MT-gH0hvE0SjYFxy-Bscrl7wJDFvxPRymX5nWczidaKLeHnGB2KfseEccmCOLGHWMR7A4GCKyUYNUY0TtlHLsK0eAvgP2R6hkMhNyjhPj6AEhv5unlr0B9Ya6hk6QiP9KoQzW5L_Kqihjzb6f71A

# RestTemplate timeout (ms)
lta.datamall.connect-timeout=5000
lta.datamall.read-timeout=10000
