spring.application.name=fleet_mgmt_sys
spring.datasource.url=jdbc:postgresql://localhost:5432/fleet_mgmt_db
spring.datasource.username=postgres
spring.datasource.password=noclashfleet

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

logging.level.org.springframework.boot.context.config=DEBUG